# Generated by Django 3.1.5 on 2021-02-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='game',
        ),
        migrations.RemoveField(
            model_name='platforms',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(to='main.Genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='main.Platforms'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
